#!/usr/bin/env python3
import os
import subprocess

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))

with open(f"{CURRENT_DIR}/modules.txt", "r") as modules_file:
    modules = modules_file.read().splitlines()

for module in modules:
    subprocess.run(["code", "--install-extension", module])
